### ISSUE TITLE
Update Gemfile with global path

### ISSUE THREAD

**Issue by agenteo** [shageman/the_next_big_thing#20]
Hi,

if we used bundler’s undocumented path 'components' at the top of your Gemfile it will recursively require gemspecs and you won’t need to add path individually for each gem anymore. What do you think about it?

I found out this only a few days ago but couldn't contain the excitement :dancer: 
http://www.teotti.com/work/ruby/engines/2014/11/19/gemfiles-hierarchy-in-ruby-on-rails-component-based-architecture.html

**Comment by replaid** [comment]
It looks like this was resolved in https://github.com/shageman/the_next_big_thing/commit/828b3fed7a7e5bd0ecb923ec70569d601b5e05f3.
